### ISSUE TITLE
How to upload custom reference set?

### ISSUE THREAD

**Issue by TerezaClarence** [atakanekiz/CIPR-Package#6]
Dear developer of CIPR,

thank you for creating a great tool! Unfortunately, the web-based app always crushed whenever I want to upload a custom reference dataset (in the exact format as suggested on the web). I was wondering what are the options to load a custom reference set in the package? Shall I simply substitute:

```
CIPR(input_dat = allmarkers,
     comp_method = "logfc_dot_product", 
     reference = "./custom_reference.txt", 
     plot_ind = T,
     plot_top = F, 
     global_results_obj = T, 
     global_plot_obj = T,
     # axis.text.x=element_text(color="red") # arguments to pass to ggplot2::theme() to change plotting parameters
     )
```
Thank you very much!

Best regards,
Tereza

**Comment by atakanekiz** [comment]
Hi Tereza,

Thank you for using our tool. Could you please share with me a shortened custom reference file you are trying to submit? If there is sensitive information/annotations there, you can replace those with placeholder names. That will help me troubleshoot the problem.

**Comment by TerezaClarence** [comment]
Hello,

thank you so much for such a swift reply. I am trying to upload this reference from AllenBrainInstitute M1:
**[](https://portal.brain-map.org/atlases-and-data/rnaseq/human-m1-10x)** 
>> _Gene Expression by Cell Type, medians | 27 MB | .csv | Gene expression aggregated per cell type, calculated as medians._

Best regards,
Tereza


[Gene Expression by Cell Type, medians](https://idk-etl-prod-download-bucket.s3.amazonaws.com/aibs_human_m1_10x/medians.csv)	27 MB	.csv	Gene expression aggregated per cell type, calculated as medians.

**Comment by atakanekiz** [comment]
Can you try again after renaming the first column from `feature` to `Gene` and let me know if it solves the problem?

**Comment by TerezaClarence** [comment]
I have changed that as suggested but still getting the same error: 
```
> getwd()
[1] "~/CIPR"
>   file_ref = paste(path_ref,'medians_M1avgex_ref.csv',sep='')
> file_ref
[2] "~/Annotation_files/medians_M1avgex_ref.csv"
>   CIPR(input_dat = allmarkers,
+        comp_method = "logfc_dot_product", 
+        reference = file_ref, 
+        plot_ind = T,
+        plot_top = F)
Preparing input data
Preparing reference data
"reference" argument accepts of the following: "mmrnaseq",  "blueprint", "hpca", "dice", "hema", "hsrnaseq", "custom"
Error in CIPR(input_dat = allmarkers, comp_method = "logfc_dot_product":
```
Am I missing something trivial that I can't see?

Thank you,
Tereza

**Comment by TerezaClarence** [comment]
Thank you so much, I think I am almost there:


```
> custom_ref_df
[1] "./medians_M1avgex_ref.txt"
> df = read.table(custom_ref_df,check.names=F, header=T, sep='\t')
> colnames(df)[1]
[1] "gene"
```

```
>     CIPR(input_dat = allmarkers,
+          comp_method = "logfc_dot_product",
+          reference="custom",
+          custom_reference = df,
+          #custom_ref_annot_path = custom_annot_df,
+          keep_top_var = 100,
+          global_results_obj = T,
+          plot_top = T)
Preparing input data
Preparing reference data
Reading custom reference data
Analyzing cluster signatures
Error in `auto_copy()`:
! `x` and `y` must share the same src.
ℹ set `copy` = TRUE (may be slow).
Run `rlang::last_error()` to see where the error occurred.
```

Is it possible to make ref_annot optional?
```
>     rlang::last_error()
<error/rlang_error>
Error in `auto_copy()`:
! `x` and `y` must share the same src.
ℹ set `copy` = TRUE (may be slow).
---
Backtrace:
 1. CIPR::CIPR(...)
 3. dplyr:::left_join.data.frame(df, ref_annot, by = c(reference_id = "short_name"))
 4. dplyr::auto_copy(x, y, copy = copy)
Run `rlang::last_trace()` to see the full context.
```

```
> rlang::last_trace()
<error/rlang_error>
Error in `auto_copy()`:
! `x` and `y` must share the same src.
ℹ set `copy` = TRUE (may be slow).
---
Backtrace:
    ▆
 1. └─CIPR::CIPR(...)
 2.   ├─dplyr::left_join(df, ref_annot, by = c(reference_id = "short_name"))
 3.   └─dplyr:::left_join.data.frame(df, ref_annot, by = c(reference_id = "short_name"))
 4.     └─dplyr::auto_copy(x, y, copy = copy)
 5.       └─rlang::abort(bullets)
> 
```

Thank you so much for your help!
Tereza

**Comment by atakanekiz** [comment]
I fixed something (8729f6bda9f9a178f77844cab9467904fb9ecdae). Can you please check again? If that doesn't work, I will work on it in more detail, but I don't think I can get to it within the next few weeks. In the meantime, I can suggest creating a mock reference annotation data frame to see if that works? Alternatively, you can try the Shiny program and export the results/figures from the web.

**Comment by TerezaClarence** [comment]
Thank you so much for your help,

unfortunately,  I still get the same error. The shiny App is now working well! It is just inconvenient for high throughput. 

Best,
Tereza

**Comment by atakanekiz** [comment]
I will fix this as soon as I can. Sorry for the trouble

**Comment by TerezaClarence** [comment]
Thank you so much! I was also wondering if there is any use limit for the Shiny Web app? It seems that the web stops working for me after > 15 iterations (I know it might be a lot) - disconnection from the server. The same thing happened yesterday.

Thank you,
Tereza

**Comment by atakanekiz** [comment]
There shouldn't be a limit for cluster numbers to be calculated actually. I wonder if something else is happening. I'll check that too. Thanks for bringing to my attention. If you are familiar with R you can run the app locally and see where it acts up for your own data. There is a separate repo for the shiny code on GitHub

**Comment by clee700** [comment]
Hello! I was working on this same issue, and I think I've fixed it. 
In the call, you should specify custom_reference (not custom_reference_path) and also specify custom_ref_annot (not custom_ref_annot_path). In the code, it looks for custom_ref_annot/custom_reference, not the path variables. This seems to have fixed it for me. 

Hope that helps!
